spring:
  application.name: renergy
  datasource:
    driver-class-name: org.postgresql.Driver
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"
    url: "${DB_URL}"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    database: postgresql
