INSERT INTO countries_continents (name, is_country, code)
VALUES
    ('Afghanistan', true, 'AFG'),
    ('Africa', false, NULL),
    ('Africa (EI)', false, NULL),
    ('Africa (Ember)', false, NULL),
    ('Albania', true, 'ALB'),
    ('Algeria', true, 'DZA'),
    ('American Samoa', true, 'ASM'),
    ('Andorra', true, 'AND'),
    ('Angola', true, 'AGO'),
    ('Anguilla', true, 'AIA'),
    ('Antigua and Barbuda', true, 'ATG'),
    ('Argentina', true, 'ARG'),
    ('Armenia', true, 'ARM'),
    ('Aruba', true, 'ABW'),
    ('Asia', false, NULL),
    ('Asia (Ember)', false, NULL),
    ('Asia Pacific (EI)', false, NULL),
    ('Australia', true, 'AUS'),
    ('Austria', true, 'AUT'),
    ('Azerbaijan', true, 'AZE'),
    ('Bahamas', true, 'BHS'),
    ('Bahrain', true, 'BHR'),
    ('Bangladesh', true, 'BGD'),
    ('Barbados', true, 'BRB'),
    ('Belarus', true, 'BLR'),
    ('Belgium', true, 'BEL'),
    ('Belize', true, 'BLZ'),
    ('Benin', true, 'BEN'),
    ('Bermuda', true, 'BMU'),
    ('Bhutan', true, 'BTN'),
    ('Bolivia', true, 'BOL'),
    ('Bonaire Sint Eustatius and Saba', true, 'BES'),
    ('Bosnia and Herzegovina', true, 'BIH'),
    ('Botswana', true, 'BWA'),
    ('Brazil', true, 'BRA'),
    ('British Virgin Islands', true, 'VGB'),
    ('Brunei', true, 'BRN'),
    ('Bulgaria', true, 'BGR'),
    ('Burkina Faso', true, 'BFA'),
    ('Burundi', true, 'BDI'),
    ('CIS (EI)', false, NULL),
    ('Cambodia', true, 'KHM'),
    ('Cameroon', true, 'CMR'),
    ('Canada', true, 'CAN'),
    ('Cape Verde', true, 'CPV'),
    ('Cayman Islands', true, 'CYM'),
    ('Central African Republic', true, 'CAF'),
    ('Central America (EI)', false, NULL),
    ('Chad', true, 'TCD'),
    ('Chile', true, 'CHL'),
    ('China', true, 'CHN'),
    ('Colombia', true, 'COL'),
    ('Comoros', true, 'COM'),
    ('Congo', true, 'COG'),
    ('Cook Islands', true, 'COK'),
    ('Costa Rica', true, 'CRI'),
    ('Code De Ivoire', true, 'CIV'),
    ('Croatia', true, 'HRV'),
    ('Cuba', true, 'CUB'),
    ('Curacao', true, 'CUW'),
    ('Cyprus', true, 'CYP'),
    ('Czechia', true, 'CZE'),
    ('Democratic Republic of Congo', true, 'COD'),
    ('Denmark', true, 'DNK'),
    ('Djibouti', true, 'DJI'),
    ('Dominica', true, 'DMA'),
    ('Dominican Republic', true, 'DOM'),
    ('East Timor', true, 'TLS'),
    ('Eastern Africa (EI)', false, NULL),
    ('Ecuador', true, 'ECU'),
    ('Egypt', true, 'EGY'),
    ('El Salvador', true, 'SLV'),
    ('Equatorial Guinea', true, 'GNQ'),
    ('Eritrea', true, 'ERI'),
    ('Estonia', true, 'EST'),
    ('Eswatini', true, 'SWZ'),
    ('Ethiopia', true, 'ETH'),
    ('Europe', false, NULL),
    ('Europe (EI)', false, NULL),
    ('Europe (Ember)', false, NULL),
    ('European Union (27)', false, NULL),
    ('Falkland Islands', true, 'FLK'),
    ('Faroe Islands', true, 'FRO'),
    ('Fiji', true, 'FJI'),
    ('Finland', true, 'FIN'),
    ('France', true, 'FRA'),
    ('French Guiana', true, 'GUF'),
    ('French Polynesia', true, 'PYF'),
    ('G2false (Ember)', false, NULL),
    ('G7 (Ember)', false, NULL),
    ('Gabon', true, 'GAB'),
    ('Gambia', true, 'GMB'),
    ('Georgia', true, 'GEO'),
    ('Germany', true, 'DEU'),
    ('Ghana', true, 'GHA'),
    ('Gibraltar', true, 'GIB'),
    ('Greece', true, 'GRC'),
    ('Greenland', true, 'GRL'),
    ('Grenada', true, 'GRD'),
    ('Guadeloupe', true, 'GLP'),
    ('Guam', true, 'GUM'),
    ('Guatemala', true, 'GTM'),
    ('Guinea', true, 'GIN'),
    ('Guinea-Bissau', true, 'GNB'),
    ('Guyana', true, 'GUY'),
    ('Haiti', true, 'HTI'),
    ('High-income countries', false, NULL),
    ('Honduras', true, 'HND'),
    ('Hong Kong', true, 'HKG'),
    ('Hungary', true, 'HUN'),
    ('Iceland', true, 'ISL'),
    ('India', true, 'IND'),
    ('Indonesia', true, 'IDN'),
    ('Iran', true, 'IRN'),
    ('Iraq', true, 'IRQ'),
    ('Ireland', true, 'IRL'),
    ('Israel', true, 'ISR'),
    ('Italy', true, 'ITA'),
    ('Jamaica', true, 'JAM'),
    ('Japan', true, 'JPN'),
    ('Jordan', true, 'JOR'),
    ('Kazakhstan', true, 'KAZ'),
    ('Kenya', true, 'KEN'),
    ('Kiribati', true, 'KIR'),
    ('Kosovo', true, 'XKX'),
    ('Kuwait', true, 'KWT'),
    ('Kyrgyzstan', true, 'KGZ'),
    ('Laos', true, 'LAO'),
    ('Latin America and Caribbean (Ember)', false, NULL),
    ('Latvia', true, 'LVA'),
    ('Lebanon', true, 'LBN'),
    ('Lesotho', true, 'LSO'),
    ('Liberia', true, 'LBR'),
    ('Libya', true, 'LBY'),
    ('Lithuania', true, 'LTU'),
    ('Low-income countries', false, NULL),
    ('Lower-middle-income countries', false, NULL),
    ('Luxembourg', true, 'LUX'),
    ('Macao', true, 'MAC'),
    ('Madagascar', true, 'MDG'),
    ('Malawi', true, 'MWI'),
    ('Malaysia', true, 'MYS'),
    ('Maldives', true, 'MDV'),
    ('Mali', true, 'MLI'),
    ('Malta', true, 'MLT'),
    ('Marshall Islands', true, 'MHL'),
    ('Martinique', true, 'MTQ'),
    ('Mauritania', true, 'MRT'),
    ('Mauritius', true, 'MUS'),
    ('Mayotte', true, 'MYT'),
    ('Mexico', true, 'MEX'),
    ('Micronesia (country)', true, 'FSM'),
    ('Middle Africa (EI)', false, NULL),
    ('Middle East (EI)', false, NULL),
    ('Middle East (Ember)', false, NULL),
    ('Moldova', true, 'MDA'),
    ('Mongolia', true, 'MNG'),
    ('Montenegro', true, 'MNE'),
    ('Montserrat', true, 'MSR'),
    ('Morocco', true, 'MAR'),
    ('Mozambique', true, 'MOZ'),
    ('Myanmar', true, 'MMR'),
    ('Namibia', true, 'NAM'),
    ('Nauru', true, 'NRU'),
    ('Nepal', true, 'NPL'),
    ('Netherlands', true, 'NLD'),
    ('New Caledonia', true, 'NCL'),
    ('New Zealand', true, 'NZL'),
    ('Nicaragua', true, 'NIC'),
    ('Niger', true, 'NER'),
    ('Nigeria', true, 'NGA'),
    ('Niue', true, 'NIU'),
    ('Non-OECD (EI)', false, NULL),
    ('North America', false, NULL),
    ('North America (EI)', false, NULL),
    ('North America (Ember)', false, NULL),
    ('North Korea', true, 'PRK'),
    ('North Macedonia', true, 'MKD'),
    ('Norway', true, 'NOR'),
    ('OECD (EI)', false, NULL),
    ('OECD (Ember)', false, NULL),
    ('Oceania', false, NULL),
    ('Oceania (Ember)', false, NULL),
    ('Oman', true, 'OMN'),
    ('Pakistan', true, 'PAK'),
    ('Palau', true, 'PLW'),
    ('Palestine', true, 'PSE'),
    ('Panama', true, 'PAN'),
    ('Papua New Guinea', true, 'PNG'),
    ('Paraguay', true, 'PRY'),
    ('Peru', true, 'PER'),
    ('Philippines', true, 'PHL'),
    ('Poland', true, 'POL'),
    ('Portugal', true, 'PRT'),
    ('Puerto Rico', true, 'PRI'),
    ('Qatar', true, 'QAT'),
    ('Reunion', true, 'REU'),
    ('Romania', true, 'ROU'),
    ('Russia', true, 'RUS'),
    ('Rwanda', true, 'RWA'),
    ('Saint Barthelemy', true, 'BLM'),
    ('Saint Helena', true, 'SHN'),
    ('Saint Kitts and Nevis', true, 'KNA'),
    ('Saint Lucia', true, 'LCA'),
    ('Saint Martin (French part)', true, 'MAF'),
    ('Saint Pierre and Miquelon', true, 'SPM'),
    ('Saint Vincent and the Grenadines', true, 'VCT'),
    ('Samoa', true, 'WSM'),
    ('Sao Tome and Principe', true, 'STP'),
    ('Saudi Arabia', true, 'SAU'),
    ('Senegal', true, 'SEN'),
    ('Serbia', true, 'SRB'),
    ('Seychelles', true, 'SYC'),
    ('Sierra Leone', true, 'SLE'),
    ('Singapore', true, 'SGP'),
    ('Slovakia', true, 'SVK'),
    ('Slovenia', true, 'SVN'),
    ('Solomon Islands', true, 'SLB'),
    ('Somalia', true, 'SOM'),
    ('South Africa', true, 'ZAF'),
    ('South America', false, NULL),
    ('South Korea', true, 'KOR'),
    ('South Sudan', true, 'SSD'),
    ('South and Central America (EI)', false, NULL),
    ('Spain', true, 'ESP'),
    ('Sri Lanka', true, 'LKA'),
    ('Sudan', true, 'SDN'),
    ('Suriname', true, 'SUR'),
    ('Sweden', true, 'SWE'),
    ('Switzerland', true, 'CHE'),
    ('Syria', true, 'SYR'),
    ('Taiwan', true, 'TWN'),
    ('Tajikistan', true, 'TJK'),
    ('Tanzania', true, 'TZA'),
    ('Thailand', true, 'THA'),
    ('Togo', true, 'TGO'),
    ('Tokelau', true, 'TKL'),
    ('Tonga', true, 'TON'),
    ('Trinidad and Tobago', true, 'TTO'),
    ('Tunisia', true, 'TUN'),
    ('Turkey', true, 'TUR'),
    ('Turkmenistan', true, 'TKM'),
    ('Turks and Caicos Islands', true, 'TCA'),
    ('Tuvalu', true, 'TUV'),
    ('USSR', true, NULL),
    ('Uganda', true, 'UGA'),
    ('Ukraine', true, 'UKR'),
    ('United Arab Emirates', true, 'ARE'),
    ('United Kingdom', true, 'GBR'),
    ('United States', true, 'USA'),
    ('United States Virgin Islands', true, 'VIR'),
    ('Upper-middle-income countries', false, NULL),
    ('Uruguay', true, 'URY'),
    ('Uzbekistan', true, 'UZB'),
    ('Vanuatu', true, 'VUT'),
    ('Venezuela', true, 'VEN'),
    ('Vietnam', true, 'VNM'),
    ('Western Africa (EI)', false, NULL),
    ('Western Sahara', true, 'ESH'),
    ('World', true, NULL),
    ('Yemen', true, 'YEM'),
    ('Zambia', true, 'ZMB'),
    ('Zimbabwe', true, 'ZWE');